### ISSUE TITLE
Mod suggestion: Dynamic Trees

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#71] opened 2020-07-17 01:27 UTC
### Description

A mod that makes trees more realistic. All trees have their own unique seed item that can be planted and will grow, like normal saplings. But with the seeds, you can actually See their growth stages. Trees also drop seeds from their leaves every so often, allowing them to spread. Cutting a tree down will also make the tree actually fall down, rather then just staying a float like magic. :P

Example of a Dynamic Oak Tree:
![2020-07-16_18 43 32](https://user-images.githubusercontent.com/51277766/87739265-4b432400-c794-11ea-9050-da9d9af96609.png)

### Details

- Does a Forge version of this mod exist? Yes.
    - If yes, what is the link to the github/curseforge? https://www.curseforge.com/minecraft/mc-mods/dynamictrees
- Does a Fabric version of this mod exist for an older MC version? No.
    - If yes, what is the link to the github/curseforge? N/A

**Comment by Martmists-GH** [comment] 2020-07-17 14:36
Closing as duplicate of #16

**Closed as completed by Martmists-GH** 2020-07-17 14:36 UTC
Labels: duplicate

**Comment by MagmaSlime123** [comment] 2020-09-07 05:04
Sorry.
