### ISSUE TITLE
Mod suggestion: Twilight Forest

### ISSUE THREAD

**Issue by MagmaSlime123** [martmists-gh/fabric-mod-wishlist#75] opened 2020-09-07 05:09 UTC
### Description

Adds a magical forest-like dimension with many new trees, bosses, mobs, building blocks, mobs, and MUCH, MUCH more.

### Details

- Does a Forge version of this mod exist? Yes.
    - If yes, what is the link to the github/curseforge? https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest
- Does a Fabric version of this mod exist for an older MC version? No.
    - If yes, what is the link to the github/curseforge? N/A

**Comment by Martmists-GH** [comment] 2020-09-07 11:57
Closing as duplicate of #56

**Closed as completed by Martmists-GH** 2020-09-07 11:57 UTC
Labels: Needs Categorization

**Comment by MagmaSlime123** [comment] 2020-09-07 15:03
Sorry.
